### ISSUE TITLE
Add fake Http facade

### ISSUE THREAD

**Issue by SamSalvatico** [NoelDeMartin/laravel-dusk-mocking#30]
Laravel-Dusk-mocking version: v6.5.2
Laravel Version: v8.43.0
Laravel Sail Version: v1.7.0
## Description
I have an application that runs using Laravel Sail and needs to make external Http requests to be able to login, so I tried to fake Http facade but the `sail dusk` command throws this error
```
1) Tests\Browser\ExampleTest::testBasicExample
Exception: Unable to retrieve mock for [Illuminate\Support\Facades\Http].
```

The test code is: 
```
use Illuminate\Support\Facades\Http;
use NoelDeMartin\LaravelDusk\Browser;
use Tests\DuskTestCase;

class ExampleTest extends DuskTestCase
{
    /**
     * A basic browser test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $http = $browser->fake(Http::class);
            //make things with http instance
            $browser->visit('/login')
                ->type('username', 'e@mail.com')
                ->type('password', 'password')
                ->press('Login')->dump();
            //->assertPathIs(RouteServiceProvider::HOME);
        });
    }
}
```

I added the newBrowser method in DuskTestCase
```
protected function newBrowser($driver)
    {
        Browser::$javascriptRequestsTimeout = 5;
        return new Browser($driver);
    }
```
Also tried to edit `Browser::$javascriptRequestsTimeout` setting it to 30.

Is it a problem of my environment or it is not possible to fake Http facade?

**Comment by SamSalvatico** [comment]
I'm sorry, I didn't read the logs that say:
```
 local.ERROR: Serialization of 'Closure' is not allowed {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /var/www/html/vendor/noeldemartin/laravel-dusk-mocking/src/Driver.php:151)
[stacktrace]
#0 /var/www/html/vendor/noeldemartin/laravel-dusk-mocking/src/Driver.php(151): serialize()
#1 /var/www/html/vendor/noeldemartin/laravel-dusk-mocking/src/Drivers/CookiesDriver.php(45): NoelDeMartin\\LaravelDusk\\Driver->serialize()
#2 /var/www/html/vendor/noeldemartin/laravel-dusk-mocking/src/Driver.php(64): NoelDeMartin\\LaravelDusk\\Drivers\\CookiesDriver->persist()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(191): NoelDeMartin\\LaravelDusk\\Driver->save()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Support\\Manager->__call()
#5 /var/www/html/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Middleware/SaveMocking.php(21): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): NoelDeMartin\\LaravelDusk\\Http\\Middleware\\SaveMocking->handle()
#7 /var/www/html/vendor/noeldemartin/laravel-dusk-mocking/src/Http/Middleware/StartMocking.php(21....
```

So it is related to the Limitation part in the readme file
